In [1]:
import pandas as pd
from color_pages import *
from tqdm import tqdm

import json
tqdm.pandas()




%load_ext autoreload
%autoreload 2

In [2]:
exemple = "/dlabdata1/tsoares/wikidumps/simplewiki-NS0-20231001/eval/pages/332374_9111024.html"
print(exemple)

/dlabdata1/tsoares/wikidumps/simplewiki-NS0-20231001/eval/pages/332374_9111024.html

In [3]:
#copy the example and past it in root folder

In [3]:
scored_simple_5 =pd.read_parquet("/dlabdata1/boulenge/wikidumps_data/scored_data/simple_5_scored.parquet")

In [7]:
display(scored_simple_5.head())

,source_title,source_ID,target_title,context,insert_indices,moved_insertion_marker,link_sentence,link_text,section,mention_present,source_lead,first_version,second_version,direct_match,missing_category,all_contexts,target_lead,idx
0,List_of_mayors_in_Norway_2023%E2%80%932027,1052251,Møre og Romsdal,None,[26],None,"Hustadvika. KrF, and Centre Party; Nils Christ...",Møre og Romsdal,Lead,None,"In September and October 2023, every municipal...",9114883,9114892,None,missing_span,"[{'context': 'In September and October 2023, e...",Møre og Romsdal is a county in Norway. Norway ...,0
1,Puffin_Rock,954730,Disney XD,None,[1],None,It follows the adventures of two young puffins...,Disney XD,Lead,None,Puffin Rock is a Irish animated children's tel...,8673424,9134125,None,missing_mention_with_sentence_modifications,[{'context': 'Puffin Rock is a Irish animated ...,Disney XD is an American digital cable and sat...,1
2,Kevin_Costner,73022,United States,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,USA,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...,"The United States of America, commonly known a...",2
3,Kevin_Costner,73022,Eliot Ness,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,Eliot Ness,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...,Eliot Ness was an American Prohibition agent. ...,3
4,Kevin_Costner,73022,Academy Award for Best Director,None,[0],None,{{Infobox actor. | name = Kevin Costner. | ima...,Academy Award for Best Director,Lead,None,"Kevin Michael Costner (born January 18, 1955) ...",9078665,9093331,None,missing_span,[{'context': 'Kevin Michael Costner (born Janu...,"The Academy Award for Best Directing, usually ...",4

In [4]:
display(scored_simple_5['missing_category'].value_counts())

missing_category
missing_span                                   12
missing_mention_with_sentence_modifications     9
missing_mention                                 3
Name: count, dtype: int64

In [16]:
colouring_pipeline(
    scored_simple_5,
    'colored_htmls',
    '/dlabdata1/tsoares/wikidumps/simplewiki-NS0-20231001/eval/pages',
    'simple',
)

Coloring with grey_to_red
Smoothing param: 1

  0%|          | 0/537 [00:00<?, ?it/s]

100%|██████████| 537/537 [00:00<00:00, 1369.99it/s]

Style: highlight

100%|██████████| 537/537 [00:45<00:00, 11.93it/s]

In [5]:
def get_url(source_title, page_id, version):
    return f"https://simple.wikipedia.org/w/index.php?title={source_title}&curid={page_id}&oldid={version}"

In [6]:
def get_file_name(source_ID, version):
    return f"{source_ID}_{version}.html"

In [9]:
url_df = pd.DataFrame()

url_df['title'] = scored_simple_5['source_title']
url_df['first_file_name'] = scored_simple_5[['source_ID', 'first_version']].apply(lambda x: get_file_name(x['source_ID'], x['first_version']), axis=1)
url_df['second_file_name'] = scored_simple_5[['source_ID', 'second_version']].apply(lambda x: get_file_name(x['source_ID'], x['second_version']), axis=1)
url_df['first_version_url'] = scored_simple_5[['source_title', 'source_ID', 'first_version']].apply(lambda x: get_url(x['source_title'], x['source_ID'], x['first_version']), axis=1)
url_df['second_version_url'] = scored_simple_5[['source_title', 'source_ID', 'second_version']].apply(lambda x: get_url(x['source_title'], x['source_ID'], x['second_version']), axis=1)

display(url_df)

,title,first_file_name,second_file_name,first_version_url,second_version_url
0,List_of_mayors_in_Norway_2023%E2%80%932027,1052251_9114883.html,1052251_9114892.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
1,Puffin_Rock,954730_8673424.html,954730_9134125.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
2,Kevin_Costner,73022_9078665.html,73022_9093331.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
3,Kevin_Costner,73022_9078665.html,73022_9093331.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
4,Kevin_Costner,73022_9078665.html,73022_9093331.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
5,Kevin_Costner,73022_9078665.html,73022_9093331.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
6,Kevin_Costner,73022_9078665.html,73022_9093331.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
7,Kevin_Costner,73022_9078665.html,73022_9093331.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
8,Kevin_Costner,73022_9078665.html,73022_9093331.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
9,Tancredo_Neves,803963_9135988.html,803963_9135991.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
10,The_Snuts,1041893_9030083.html,1041893_9039855.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
11,The_Snuts,1041893_9030083.html,1041893_9039855.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
12,The_Snuts,1041893_9030083.html,1041893_9039855.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
13,The_Snuts,1041893_9030083.html,1041893_9039855.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
14,The_Snuts,1041893_9030083.html,1041893_9039855.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
15,Konstantin_Chernenko,18126_9106049.html,18126_9143707.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
16,Konstantin_Chernenko,18126_9106049.html,18126_9143707.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
17,2023,623621_9044036.html,623621_9046693.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
18,2023,623621_9044036.html,623621_9046693.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
19,2023,623621_9044036.html,623621_9046693.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
20,2023,623621_9044036.html,623621_9046693.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
21,Public_broadcasting,391475_7911479.html,391475_9118661.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
22,Public_broadcasting,391475_7911479.html,391475_9118661.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...
23,Public_broadcasting,391475_7911479.html,391475_9118661.html,https://simple.wikipedia.org/w/index.php?title...,https://simple.wikipedia.org/w/index.php?title...

In [10]:
for i, first_verison_url in enumerate(url_df['first_version_url']):
    print(i)
    print(url_df['first_file_name'][i])
    print(first_verison_url)

0
1052251_9114883.html
https://simple.wikipedia.org/w/index.php?title=List_of_mayors_in_Norway_2023%E2%80%932027&curid=1052251&oldid=9114883
1
954730_8673424.html
https://simple.wikipedia.org/w/index.php?title=Puffin_Rock&curid=954730&oldid=8673424
2
73022_9078665.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&curid=73022&oldid=9078665
3
73022_9078665.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&curid=73022&oldid=9078665
4
73022_9078665.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&curid=73022&oldid=9078665
5
73022_9078665.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&curid=73022&oldid=9078665
6
73022_9078665.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&curid=73022&oldid=9078665
7
73022_9078665.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&curid=73022&oldid=9078665
8
73022_9078665.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&curid=73022&oldid=9078665
9
803963_9135988.html
https://simple.wikipedia.org/w/index.php?title=Tancredo_Neves&curid=803963&oldid=9135988
10
1041893_9030083.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&curid=1041893&oldid=9030083
11
1041893_9030083.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&curid=1041893&oldid=9030083
12
1041893_9030083.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&curid=1041893&oldid=9030083
13
1041893_9030083.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&curid=1041893&oldid=9030083
14
1041893_9030083.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&curid=1041893&oldid=9030083
15
18126_9106049.html
https://simple.wikipedia.org/w/index.php?title=Konstantin_Chernenko&curid=18126&oldid=9106049
16
18126_9106049.html
https://simple.wikipedia.org/w/index.php?title=Konstantin_Chernenko&curid=18126&oldid=9106049
17
623621_9044036.html
https://simple.wikipedia.org/w/index.php?title=2023&curid=623621&oldid=9044036
18
623621_9044036.html
https://simple.wikipedia.org/w/index.php?title=2023&curid=623621&oldid=9044036
19
623621_9044036.html
https://simple.wikipedia.org/w/index.php?title=2023&curid=623621&oldid=9044036
20
623621_9044036.html
https://simple.wikipedia.org/w/index.php?title=2023&curid=623621&oldid=9044036
21
391475_7911479.html
https://simple.wikipedia.org/w/index.php?title=Public_broadcasting&curid=391475&oldid=7911479
22
391475_7911479.html
https://simple.wikipedia.org/w/index.php?title=Public_broadcasting&curid=391475&oldid=7911479
23
391475_7911479.html
https://simple.wikipedia.org/w/index.php?title=Public_broadcasting&curid=391475&oldid=7911479

In [11]:
for i, second_version_url in enumerate(url_df['second_version_url']):
    print(i)
    print(url_df['second_file_name'][i])
    print(second_version_url)

0
1052251_9114892.html
https://simple.wikipedia.org/w/index.php?title=List_of_mayors_in_Norway_2023%E2%80%932027&oldid=9114892
1
818327_9126510.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126510
2
818327_9126510.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126510
3
38298_9150709.html
https://simple.wikipedia.org/w/index.php?title=Plow&oldid=9150709
4
986335_9138326.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9138326
5
986335_9138326.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9138326
6
3581_9131902.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9131902
7
3581_9131902.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9131902
8
1020279_9141227.html
https://simple.wikipedia.org/w/index.php?title=American_eel&oldid=9141227
9
389821_9107628.html
https://simple.wikipedia.org/w/index.php?title=Battle_of_the_Plains_of_Abraham&oldid=9107628
10
389821_9107628.html
https://simple.wikipedia.org/w/index.php?title=Battle_of_the_Plains_of_Abraham&oldid=9107628
11
389821_9107628.html
https://simple.wikipedia.org/w/index.php?title=Battle_of_the_Plains_of_Abraham&oldid=9107628
12
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
13
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
14
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
15
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
16
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
17
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
18
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
19
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
20
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
21
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
22
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
23
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
24
14264_9111832.html
https://simple.wikipedia.org/w/index.php?title=DC_Comics&oldid=9111832
25
221991_9113731.html
https://simple.wikipedia.org/w/index.php?title=3rd_millennium&oldid=9113731
26
221991_9113731.html
https://simple.wikipedia.org/w/index.php?title=3rd_millennium&oldid=9113731
27
221991_9113731.html
https://simple.wikipedia.org/w/index.php?title=3rd_millennium&oldid=9113731
28
1052901_9143317.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9143317
29
1052901_9143317.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9143317
30
1052901_9143317.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9143317
31
1052901_9143317.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9143317
32
954730_9134125.html
https://simple.wikipedia.org/w/index.php?title=Puffin_Rock&oldid=9134125
33
3061_9117078.html
https://simple.wikipedia.org/w/index.php?title=Cymru_Premier&oldid=9117078
34
1052901_9118971.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9118971
35
646739_9094974.html
https://simple.wikipedia.org/w/index.php?title=2026_FIFA_World_Cup&oldid=9094974
36
646739_9094974.html
https://simple.wikipedia.org/w/index.php?title=2026_FIFA_World_Cup&oldid=9094974
37
646739_9094974.html
https://simple.wikipedia.org/w/index.php?title=2026_FIFA_World_Cup&oldid=9094974
38
1056147_9142227.html
https://simple.wikipedia.org/w/index.php?title=Paul_Rigoux&oldid=9142227
39
1052901_9118706.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9118706
40
1052901_9118706.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9118706
41
3581_9145095.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9145095
42
14230_9093214.html
https://simple.wikipedia.org/w/index.php?title=16th_century&oldid=9093214
43
14230_9093214.html
https://simple.wikipedia.org/w/index.php?title=16th_century&oldid=9093214
44
14230_9093214.html
https://simple.wikipedia.org/w/index.php?title=16th_century&oldid=9093214
45
14230_9093214.html
https://simple.wikipedia.org/w/index.php?title=16th_century&oldid=9093214
46
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
47
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
48
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
49
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
50
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
51
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
52
10317_9141189.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest&oldid=9141189
53
365649_9124116.html
https://simple.wikipedia.org/w/index.php?title=Beauty_and_the_Beast_%281991_movie%29&oldid=9124116
54
365649_9124116.html
https://simple.wikipedia.org/w/index.php?title=Beauty_and_the_Beast_%281991_movie%29&oldid=9124116
55
1055212_9134767.html
https://simple.wikipedia.org/w/index.php?title=Polish%E2%80%93Lithuanian%E2%80%93Muscovite_Commonwealth&oldid=9134767
56
1055212_9134767.html
https://simple.wikipedia.org/w/index.php?title=Polish%E2%80%93Lithuanian%E2%80%93Muscovite_Commonwealth&oldid=9134767
57
1055212_9134767.html
https://simple.wikipedia.org/w/index.php?title=Polish%E2%80%93Lithuanian%E2%80%93Muscovite_Commonwealth&oldid=9134767
58
1055212_9134767.html
https://simple.wikipedia.org/w/index.php?title=Polish%E2%80%93Lithuanian%E2%80%93Muscovite_Commonwealth&oldid=9134767
59
1055212_9134767.html
https://simple.wikipedia.org/w/index.php?title=Polish%E2%80%93Lithuanian%E2%80%93Muscovite_Commonwealth&oldid=9134767
60
1055212_9134767.html
https://simple.wikipedia.org/w/index.php?title=Polish%E2%80%93Lithuanian%E2%80%93Muscovite_Commonwealth&oldid=9134767
61
511665_9097666.html
https://simple.wikipedia.org/w/index.php?title=2023_Cricket_World_Cup&oldid=9097666
62
511665_9097666.html
https://simple.wikipedia.org/w/index.php?title=2023_Cricket_World_Cup&oldid=9097666
63
511665_9097666.html
https://simple.wikipedia.org/w/index.php?title=2023_Cricket_World_Cup&oldid=9097666
64
136519_9128446.html
https://simple.wikipedia.org/w/index.php?title=Ronaldinho&oldid=9128446
65
136519_9128446.html
https://simple.wikipedia.org/w/index.php?title=Ronaldinho&oldid=9128446
66
136519_9128446.html
https://simple.wikipedia.org/w/index.php?title=Ronaldinho&oldid=9128446
67
637013_9096054.html
https://simple.wikipedia.org/w/index.php?title=Chief_Justice_of_the_Philippines&oldid=9096054
68
623621_9142067.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9142067
69
623621_9142067.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9142067
70
559688_9115101.html
https://simple.wikipedia.org/w/index.php?title=Eva_Vik&oldid=9115101
71
559688_9115101.html
https://simple.wikipedia.org/w/index.php?title=Eva_Vik&oldid=9115101
72
559688_9115101.html
https://simple.wikipedia.org/w/index.php?title=Eva_Vik&oldid=9115101
73
1016646_9146067.html
https://simple.wikipedia.org/w/index.php?title=Renaissance_%28Lionel_Richie_album%29&oldid=9146067
74
1052863_9141988.html
https://simple.wikipedia.org/w/index.php?title=Kostruba_Anatoliy&oldid=9141988
75
332374_9114927.html
https://simple.wikipedia.org/w/index.php?title=Loreen&oldid=9114927
76
1037087_9122690.html
https://simple.wikipedia.org/w/index.php?title=Student_World_Impact_Film_Festival&oldid=9122690
77
1037087_9122690.html
https://simple.wikipedia.org/w/index.php?title=Student_World_Impact_Film_Festival&oldid=9122690
78
1037087_9122690.html
https://simple.wikipedia.org/w/index.php?title=Student_World_Impact_Film_Festival&oldid=9122690
79
1037087_9122690.html
https://simple.wikipedia.org/w/index.php?title=Student_World_Impact_Film_Festival&oldid=9122690
80
986335_9147269.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9147269
81
1052901_9134705.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9134705
82
1052901_9134705.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9134705
83
1056761_9147518.html
https://simple.wikipedia.org/w/index.php?title=Burmese_cat&oldid=9147518
84
1056761_9147518.html
https://simple.wikipedia.org/w/index.php?title=Burmese_cat&oldid=9147518
85
1056761_9147518.html
https://simple.wikipedia.org/w/index.php?title=Burmese_cat&oldid=9147518
86
986335_9138325.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9138325
87
986335_9138325.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9138325
88
105309_9108657.html
https://simple.wikipedia.org/w/index.php?title=Jeremy_Hunt&oldid=9108657
89
105309_9108657.html
https://simple.wikipedia.org/w/index.php?title=Jeremy_Hunt&oldid=9108657
90
9287_9126467.html
https://simple.wikipedia.org/w/index.php?title=Alabama&oldid=9126467
91
258169_9097926.html
https://simple.wikipedia.org/w/index.php?title=Motorboat&oldid=9097926
92
434285_9137850.html
https://simple.wikipedia.org/w/index.php?title=The_War_of_the_Worlds&oldid=9137850
93
1052901_9120399.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9120399
94
1052901_9120399.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9120399
95
209520_9099953.html
https://simple.wikipedia.org/w/index.php?title=1st_millennium&oldid=9099953
96
209520_9099953.html
https://simple.wikipedia.org/w/index.php?title=1st_millennium&oldid=9099953
97
209520_9099953.html
https://simple.wikipedia.org/w/index.php?title=1st_millennium&oldid=9099953
98
562855_9128884.html
https://simple.wikipedia.org/w/index.php?title=Gautam&oldid=9128884
99
818327_9126798.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126798
100
818327_9126798.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126798
101
818327_9126798.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126798
102
818327_9126798.html
https://simple.wikipedia.org/w/index.php?title=Patricia_Greene&oldid=9126798
103
592497_9127582.html
https://simple.wikipedia.org/w/index.php?title=Lost_in_Space&oldid=9127582
104
428385_9107653.html
https://simple.wikipedia.org/w/index.php?title=AMC_%28TV_channel%29&oldid=9107653
105
428385_9107653.html
https://simple.wikipedia.org/w/index.php?title=AMC_%28TV_channel%29&oldid=9107653
106
428385_9107653.html
https://simple.wikipedia.org/w/index.php?title=AMC_%28TV_channel%29&oldid=9107653
107
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
108
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
109
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
110
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
111
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
112
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
113
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
114
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
115
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
116
198155_9105175.html
https://simple.wikipedia.org/w/index.php?title=Lichen&oldid=9105175
117
984603_9123132.html
https://simple.wikipedia.org/w/index.php?title=Laurent_Mauvignier&oldid=9123132
118
45104_9109916.html
https://simple.wikipedia.org/w/index.php?title=Western_Bloc&oldid=9109916
119
794227_9152217.html
https://simple.wikipedia.org/w/index.php?title=Candy_Carson&oldid=9152217
120
391475_9118661.html
https://simple.wikipedia.org/w/index.php?title=Public_broadcasting&oldid=9118661
121
391475_9118661.html
https://simple.wikipedia.org/w/index.php?title=Public_broadcasting&oldid=9118661
122
391475_9118661.html
https://simple.wikipedia.org/w/index.php?title=Public_broadcasting&oldid=9118661
123
623621_9046693.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9046693
124
623621_9046693.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9046693
125
623621_9046693.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9046693
126
623621_9046693.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9046693
127
18126_9143707.html
https://simple.wikipedia.org/w/index.php?title=Konstantin_Chernenko&oldid=9143707
128
18126_9143707.html
https://simple.wikipedia.org/w/index.php?title=Konstantin_Chernenko&oldid=9143707
129
1041893_9039855.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&oldid=9039855
130
1041893_9039855.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&oldid=9039855
131
1041893_9039855.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&oldid=9039855
132
1041893_9039855.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&oldid=9039855
133
1041893_9039855.html
https://simple.wikipedia.org/w/index.php?title=The_Snuts&oldid=9039855
134
803963_9135991.html
https://simple.wikipedia.org/w/index.php?title=Tancredo_Neves&oldid=9135991
135
73022_9093331.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&oldid=9093331
136
73022_9093331.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&oldid=9093331
137
73022_9093331.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&oldid=9093331
138
73022_9093331.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&oldid=9093331
139
73022_9093331.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&oldid=9093331
140
73022_9093331.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&oldid=9093331
141
73022_9093331.html
https://simple.wikipedia.org/w/index.php?title=Kevin_Costner&oldid=9093331
142
773214_9108593.html
https://simple.wikipedia.org/w/index.php?title=Ren%C3%A9e_Elise_Goldsberry&oldid=9108593
143
986335_9127586.html
https://simple.wikipedia.org/w/index.php?title=Deaths_in_2023&oldid=9127586
144
3581_9133430.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9133430
145
3581_9133430.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9133430
146
3581_9133430.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9133430
147
3581_9133430.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9133430
148
3581_9133430.html
https://simple.wikipedia.org/w/index.php?title=Schizophrenia&oldid=9133430
149
867981_9123242.html
https://simple.wikipedia.org/w/index.php?title=Aggabai_Sasubai&oldid=9123242
150
867981_9123242.html
https://simple.wikipedia.org/w/index.php?title=Aggabai_Sasubai&oldid=9123242
151
867981_9123242.html
https://simple.wikipedia.org/w/index.php?title=Aggabai_Sasubai&oldid=9123242
152
460019_9095868.html
https://simple.wikipedia.org/w/index.php?title=Ruth_Davidson&oldid=9095868
153
460019_9095868.html
https://simple.wikipedia.org/w/index.php?title=Ruth_Davidson&oldid=9095868
154
674156_9121630.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9121630
155
674156_9121630.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9121630
156
674156_9121630.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9121630
157
674156_9121630.html
https://simple.wikipedia.org/w/index.php?title=June_Spencer&oldid=9121630
158
134125_9147477.html
https://simple.wikipedia.org/w/index.php?title=Clive_Charles&oldid=9147477
159
985508_9132264.html
https://simple.wikipedia.org/w/index.php?title=Tagdal&oldid=9132264
160
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
161
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
162
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
163
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
164
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
165
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
166
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
167
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
168
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
169
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
170
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
171
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
172
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
173
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
174
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
175
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
176
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
177
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
178
985914_9118337.html
https://simple.wikipedia.org/w/index.php?title=Made_You_Look&oldid=9118337
179
53002_9151066.html
https://simple.wikipedia.org/w/index.php?title=Asura&oldid=9151066
180
516773_9096377.html
https://simple.wikipedia.org/w/index.php?title=Maternal_insult&oldid=9096377
181
516773_9096377.html
https://simple.wikipedia.org/w/index.php?title=Maternal_insult&oldid=9096377
182
929556_9113396.html
https://simple.wikipedia.org/w/index.php?title=Eurovision_Song_Contest_2023&oldid=9113396
183
611187_9109327.html
https://simple.wikipedia.org/w/index.php?title=Jewel-Osco&oldid=9109327
184
1047902_9105280.html
https://simple.wikipedia.org/w/index.php?title=Panvel&oldid=9105280
185
929124_9153422.html
https://simple.wikipedia.org/w/index.php?title=Chanel_Terrero&oldid=9153422
186
704677_9103623.html
https://simple.wikipedia.org/w/index.php?title=Arab_Revolt&oldid=9103623
187
1052901_9140432.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9140432
188
1052901_9140432.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9140432
189
1052901_9140432.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9140432
190
1052901_9140432.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9140432
191
1052901_9140432.html
https://simple.wikipedia.org/w/index.php?title=2023_Israel%E2%80%93Hamas_war&oldid=9140432
192
141561_9124544.html
https://simple.wikipedia.org/w/index.php?title=Israel%E2%80%93Palestine_conflict&oldid=9124544
193
623621_9098434.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9098434
194
623621_9098434.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9098434
195
623621_9098434.html
https://simple.wikipedia.org/w/index.php?title=2023&oldid=9098434
196

In [12]:
print(len("For this reason, the person should have a thorough medical exam to rule out problems like;"))

90