In [1]:
import pandas as pd
from parsing import write_sentences_and_links
%load_ext autoreload
%autoreload 2

In [16]:
r = write_sentences_and_links(['originals/7515_9146709.html', 'originals/1003155_9150894.html', '543_9101132.html'],
                              ['test_out/7515_9146709', 'test_out/1003155_9150894', 'test_out/543_9101132'])

[
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  }
]
sentences
Time to xpath: 702.2149138450623 ms
Time to find nodes: 3.2942023277282715 ms
Time to tokenize: 5.903775691986084 ms
Time to find sub indexes: 9.187397956848145 ms
End of sentences
links
Time to xpath: 526.8492140769958 ms
Time to find links: 14.258776664733887 ms
End of links
Time to open file: 1.1424832344055176 ms
Time to create dom: 828.1387877464294 ms
Time to create document: 0.06968402862548828 ms
Time to find sections: 242.69513988494873 ms
Time to extract sentences: 722.9737043380737 ms
Time to extract links: 541.9446220397949 ms
Time to write sentences json: 0.20243358612060547 ms
Time to write links json: 0.030878067016601562 ms
Time to write to files: 0.8162593841552734 ms
Time taken to process 0 files: 2339.0266489982605 ms

[
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  }
]
sentences
Time to xpath: 200.1131830215454 ms
Time to find nodes: 1.015650749206543 ms
Time to tokenize: 1.6061253547668457 ms
Time to find sub indexes: 2.053678035736084 ms
End of sentences
links
Time to xpath: 127.77566719055176 ms
Time to find links: 8.491704940795898 ms
End of links
Time to open file: 0.5836219787597656 ms
Time to create dom: 269.50920963287354 ms
Time to create document: 0.017244338989257812 ms
Time to find sections: 95.56513261795044 ms
Time to extract sentences: 205.62483310699463 ms
Time to extract links: 136.44530725479126 ms
Time to write sentences json: 0.08712100982666016 ms
Time to write links json: 0.040502071380615234 ms
Time to write to files: 0.541508674621582 ms
Time taken to process 1 files: 708.8582620620728 ms

[
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  },
  HTMLHeadingElement {
    [Symbol(SameObject caches)]: [Object: null prototype] {
      childNodes: NodeList {},
      children: HTMLCollection {}
    }
  }
]
sentences
Time to xpath: 526.5426349639893 ms
Time to find nodes: 3.249602794647217 ms
Time to tokenize: 3.4808349609375 ms
Time to find sub indexes: 9.822711944580078 ms
End of sentences
links
Time to xpath: 233.6548638343811 ms
Time to find links: 13.183845043182373 ms
End of links
Time to open file: 0.5993599891662598 ms
Time to create dom: 285.3149814605713 ms
Time to create document: 0.009329795837402344 ms
Time to find sections: 192.44290208816528 ms
Time to extract sentences: 543.6838307380676 ms
Time to extract links: 247.02739429473877 ms
Time to write sentences json: 0.39378976821899414 ms
Time to write links json: 0.10499191284179688 ms
Time to write to files: 0.7342352867126465 ms
Time taken to process 2 files: 1270.573362827301 ms

All files processed successfully.

In [17]:
pd.read_json('test_out/7515_9146709_sentences.jsonl')

,md5,id,text,startIdx,endIdx,section,locList
0,0cf38328ae63f1cc4afb738bb2e029d5,0,Prospero and Ariel from a painting by William ...,253334,253593,Lead,"[{'start': 253334, 'end': 253372}, {'start': 2..."
1,b1313bf46003d26a785f8b839f0f81ed,1,The Tempest is one of William Shakespeare's la...,253594,253836,Lead,"[{'start': 253593, 'end': 253594}, {'start': 2..."
2,1e41c5773866b545c7368836f21d8fd1,2,It tells the story of a wizard who drives a sh...,253837,254043,Lead,"[{'start': 253835, 'end': 253860}, {'start': 2..."
3,565e56f0aa61e1ec74392392a698f3f5,3,"Unlike most of Shakespeare's plays, it does no...",254044,254131,Lead,"[{'start': 254042, 'end': 254130}]"
4,09405ba1ef477c2a88942a40f4652735,4,The play is set on an island where a magician ...,254230,254328,Story,"[{'start': 254229, 'end': 254230}, {'start': 2..."
5,3afabd6531a150fb35c5f54c8537bcb6,5,"The only company is Ariel, a spirit that Prosp...",254329,254438,Story,"[{'start': 254327, 'end': 254437}]"
6,e79f803a0d71a637fa0baf9821389bf1,6,Prospero conjures a storm that drives a ship t...,254439,254498,Story,"[{'start': 254437, 'end': 254497}]"
7,c0d10ba1b5d6e4c748746621c9628771,7,Prospero explains to Miranda that there are me...,254499,254597,Story,"[{'start': 254497, 'end': 254596}]"
8,3a9c4b01886792c7a2d2497af927b9a6,8,He used to be the Duke of Milan but was overth...,254598,254717,Story,"[{'start': 254596, 'end': 254716}]"
9,a0743334c94468791d3e36c2b0b5fac8,9,Prospero and Miranda were cast out to sea in a...,254718,254801,Story,"[{'start': 254716, 'end': 254800}]"
10,ea9566679dba5ae3086babcb15362d14,10,"Miranda was only a baby at the time, and can o...",254802,254882,Story,"[{'start': 254800, 'end': 254881}]"
11,2b34ef5ce79c567deb793b511e1198b6,11,The passengers of the ship escape onto the isl...,254883,254970,Story,"[{'start': 254881, 'end': 254882}, {'start': 2..."
12,5429d3dfbe89ec61663f48333e6596b9,12,Alonso and his son Ferdinand both think each o...,254971,255030,Story,"[{'start': 254969, 'end': 255029}]"
13,0fe8090613b51558fc92004fa9df38f0,13,"Alonso is left with his brother Sebastian, Ant...",255031,255113,Story,"[{'start': 255029, 'end': 255112}]"
14,b36a59d29b5aa44000705a6b16970d0e,14,Ferdinand meets Miranda and falls in love.,255114,255156,Story,"[{'start': 255112, 'end': 255155}]"
15,b0f601035dad1c67034ecbe67aff4790,15,Prospero tests Ferdinand to see if he is worth...,255157,255253,Story,"[{'start': 255155, 'end': 255252}]"
16,ada47a15c62654d0c849d3001fa78176,16,Antonio and Sebastian plot to kill Alonso and ...,255254,255334,Story,"[{'start': 255252, 'end': 255333}]"
17,b49385030897ad35616126b7cce2f578,17,"Meanwhile, Caliban meets two servants, Trincul...",255335,255396,Story,"[{'start': 255333, 'end': 255395}]"
18,4a78e33757467188d7c2b43b5385b864,18,He persuades them to overthrow Prospero so tha...,255397,255470,Story,"[{'start': 255395, 'end': 255469}]"
19,022ec319a0abeaeb01f89733e6a1f979,19,Prospero stops them by summoning goblins and h...,255471,255542,Story,"[{'start': 255469, 'end': 255541}]"
20,39277101ba47a023fc0294b260a1d54f,20,Ariel transforms into a fearsome bird-like cre...,255543,255707,Story,"[{'start': 255541, 'end': 255542}, {'start': 2..."
21,7be8684d37560bb83490a6d7d5df1bb5,21,They flee and eventually find Prospero.,255708,255747,Story,"[{'start': 255706, 'end': 255746}]"
22,d1cc1a42bd28222f3fb0afcc1017fa9f,22,He announces that he will forgive everyone who...,255748,255870,Story,"[{'start': 255746, 'end': 255869}]"
23,125a4c12d995a305a6f2fbb33f07f8fd,23,They react in different ways; Alonso is sorry ...,255871,255991,Story,"[{'start': 255869, 'end': 255990}]"
24,8ef89ac05aaf8e3aca2814857c1c6c5f,24,It is revealed that the ship and all the passe...,255992,256069,Story,"[{'start': 255990, 'end': 256068}]"
25,c8472d277fe0eac79ed049c822decf23,25,"Prospero sets Ariel free, and he and Miranda j...",256070,256163,Story,"[{'start': 256068, 'end': 256162}]"
26,61b078ed8363a1b7b99e8563a901f58f,26,"Prospero, the rightful Duke of Milan, who is a...",256247,256316,Main characters,"[{'start': 256246, 'end': 256247}, {'start': 2..."
27,f910c97eb6471a8928a5f6c7b1c51e71,27,"Miranda, Prospero's daughter",256317,256354,Main characters,"[{'start': 256315, 'end': 256316}, {'start': 2..."
28,0d2ddd938237d510d6cefec74ad41cb5,28,"Ariel, an airy spirit who used to be a slave o...",256355,256419,Main characters,"[{'start': 256353, 'end': 256354}, {'start': 2..."
29,7831a62bf5dd5a72f21205b5c54519c9,29,"Caliban, a savage and deformed slave",256420,256465,Main characters,"[{'start': 256418, 'end': 256419}, {'start': 2..."
30,4d910de88df03c9f21a97212ba01b1fc,30,"Alonso, King of Naples",256466,256497,Main characters,"[{'start': 256464, 'end': 256465}, {'start': 2..."
31,f3ad9e76638702ca6ccffa7d70053181,31,"Ferdinand, son of Alonso",256498,256531,Main characters,"[{'start': 256496, 'end': 256497}, {'start': 2..."
32,69ebf0f120496fa2339785755095d96c,32,"Sebastian, Alonso's brother",256532,256568,Main characters,"[{'start': 256530, 'end': 256531}, {'start': 2..."
33,279e50515d988b1523612443d97b0399,33,"Antonio, Prospero's brother, the usurping Duke...",256569,256633,Main characters,"[{'start': 256567, 'end': 256568}, {'start': 2..."
34,837fe2bb66e0e826e4efa13b37d98783,34,"Gonzalo, an honest old councillor",256634,256676,Main characters,"[{'start': 256632, 'end': 256633}, {'start': 2..."
35,a55dc2cfc0a41fe83b2bf268d18fa404,35,"Adrian and Francisco, lords",256677,256713,Main characters,"[{'start': 256675, 'end': 256676}, {'start': 2..."
36,818333b73424366eb75dbaa8d79d93fe,36,"Sycorax (unseen), a deceased sorceress and mot...",256714,256901,Main characters,"[{'start': 256712, 'end': 256713}, {'start': 2..."
37,c11405431c564cafb66d8f926f16f34c,37,The 1956 science fiction film Forbidden Planet...,257012,257316,Parallels with Forbidden Planet,"[{'start': 257011, 'end': 257012}, {'start': 2..."
38,fc3421f1b0b4a4e1970e6f19d774dcaf,38,Professor Morbius (Walter Pidgeon) and his dau...,257317,257696,Parallels with Forbidden Planet,"[{'start': 257315, 'end': 257316}, {'start': 2..."
39,0484214a7d83556a943adbf8268a1b85,39,Ariel is represented by the helpful Robbie the...,257697,257976,Parallels with Forbidden Planet,"[{'start': 257695, 'end': 257732}, {'start': 2..."
40,735453bd80614cd9d4e8b7fef2547751,40,Caliban is represented by the dangerous and in...,257977,258466,Parallels with Forbidden Planet,"[{'start': 257975, 'end': 258048}, {'start': 2..."
41,722f313e5e3869198cf56efc7ce9ab64,41,"The ""tempest"" - a word meaning ""storm"" - is in...",258548,259502,Other websites,"[{'start': 258547, 'end': 258548}, {'start': 2..."
42,6dd639277e91f2f6663ca87ea92fcec1,42,Shakespeare's The Tempest: The Wise Man as Hero,259503,259651,Other websites,"[{'start': 259501, 'end': 259502}, {'start': 2..."
43,e9140cfc7d52ccc1640f30cdbc903367,43,"The Theme of Natural Order in ""The Tempest""",259652,259791,Other websites,"[{'start': 259650, 'end': 259651}, {'start': 2..."
44,fd378b005b051c6e9a985924dd17cac9,44,Form and Disorder in The Tempest,259792,259921,Other websites,"[{'start': 259790, 'end': 259791}, {'start': 2..."
45,51fadd0d0a7c1a54b5e238cdbcde30a9,45,The Magic of Charity: A Background to Prospero,259922,260064,Other websites,"[{'start': 259920, 'end': 259921}, {'start': 2..."
46,94afbe3eb6f114efa87e223a8a8a96db,46,The Tempest Archived 2004-10-14 at the Wayback...,260065,260569,Other websites,"[{'start': 260063, 'end': 260064}, {'start': 2..."
47,d504555d0138850a397800467de37658,47,The Tempest Archived 2008-08-28 at the Wayback...,260570,260985,Other websites,"[{'start': 260568, 'end': 260569}, {'start': 2..."
48,cb409316c3f929b0351ec4704f198131,48,The Tempest - HTML version of this title.,260986,261152,Other websites,"[{'start': 260984, 'end': 260985}, {'start': 2..."
49,05a9924cdf54e32381183db01972dde1,49,Bermoothes in E. Cobham Brewer's Dictionary of...,261153,261321,Other websites,"[{'start': 261151, 'end': 261152}, {'start': 2..."
50,48ae7b05ec0b635201d4c246011bf3d5,50,Lesson plans for The Tempest Archived 2007-06-...,261322,261746,Other websites,"[{'start': 261320, 'end': 261321}, {'start': 2..."
51,ca4921197f74670f6807193f131ccf85,51,"William Strachey's ""True Reportory"" original-s...",261747,261945,Other websites,"[{'start': 261745, 'end': 261746}, {'start': 2..."
52,47322b3405d806e65a54831bc0b612db,52,This short article about the&nbsp;performing ...,305001,305850,References,"[{'start': 305000, 'end': 305001}, {'start': 3..."
53,f3dc23d05e80a7de704ac93c38fbd892,53,You can help Wikipedia by adding to it.,305851,306011,References,"[{'start': 305849, 'end': 305876}, {'start': 3..."
54,888b7a64998128787499c09c4623966d,54,This short article about literature can be ma...,306038,306858,References,"[{'start': 306037, 'end': 306038}, {'start': 3..."
55,f3dc23d05e80a7de704ac93c38fbd892,55,You can help Wikipedia by adding to it.,306859,307019,References,"[{'start': 306857, 'end': 306884}, {'start': 3..."

In [6]:
pd.read_json('test_out/7515_9146709_links.jsonl')

,link,startIdx,text,endIdx,section,sentid
0,https://simple.wikipedia.org/wiki/William_Shak...,253633,William Shakespeare's,253750,Lead,1
1,https://simple.wikipedia.org/wiki/Comedy,253756,comedies,253834,Lead,1
2,https://simple.wikipedia.org/wiki/Wizard,253860,wizard,253936,Lead,2
3,https://simple.wikipedia.org/wiki/Science_fiction,257024,science fiction,257127,Parallels with Forbidden Planet,37
4,https://simple.wikipedia.org/wiki/Forbidden_Pl...,257136,Forbidden Planet,257242,Parallels with Forbidden Planet,37
5,https://simple.wikipedia.org/wiki/Walter_Pidgeon,257342,Walter Pidgeon,257442,Parallels with Forbidden Planet,38
6,https://simple.wikipedia.org/wiki/Anne_Francis,257470,Anne Francis,257564,Parallels with Forbidden Planet,38
7,https://simple.wikipedia.org/wiki/Id,258048,id,258132,Parallels with Forbidden Planet,40
8,https://simple.wikipedia.org/wiki/Psyche,258160,psyche,258256,Parallels with Forbidden Planet,40
9,https://simple.wikipedia.org/wiki/Wayback_Machine,260324,Wayback Machine,260427,Other websites,46
10,https://simple.wikipedia.org/wiki/Project_Gute...,260454,Project Gutenberg,260563,Other websites,46
11,https://simple.wikipedia.org/wiki/Wayback_Machine,260831,Wayback Machine,260934,Other websites,47
12,https://simple.wikipedia.org/wiki/Wayback_Machine,261614,Wayback Machine,261717,Other websites,50