In [1]:
from modular_preprocessing import get_sentences_and_links
import pandas as pd

%load_ext autoreload
%autoreload 2

In [2]:
df1, df2 = get_sentences_and_links('543_9101132.html')

In [3]:
display(df1)

,id,text,startIdx,endIdx,section,locList
0,0,A noun is a kind of word (see part of speech) ...,74104,74797,lead,"[{'start': 74103, 'end': 74104}, {'start': 741..."
1,1,"In English, nouns can be singular or plural.",74797,74992,lead,"[{'start': 74796, 'end': 74800}, {'start': 748..."
2,2,Nouns often need a word called an article or d...,74992,75244,lead,"[{'start': 74991, 'end': 74992}, {'start': 749..."
3,3,These words usually do not go with other kinds...,75244,75403,lead,"[{'start': 75243, 'end': 75305}, {'start': 753..."
4,4,"(For example, people do not also describe nouns).",75403,75452,lead,"[{'start': 75402, 'end': 75451}]"
...,...,...,...,...,...,...
77,77,"Example: Take the adjective 'natural', add 'ne...",84224,84303,How adjectives become nouns,"[{'start': 84223, 'end': 84302}]"
78,78,To see a list of 100 adjectives used in Basic ...,84303,84511,How adjectives become nouns,"[{'start': 84302, 'end': 84344}, {'start': 843..."
79,79,A noun phrase is a phrase where the head word ...,84618,84720,Word order in noun phrases,"[{'start': 84617, 'end': 84618}, {'start': 846..."
80,80,"In English, the word order of most noun phrase...",84720,85110,Word order in noun phrases,"[{'start': 84719, 'end': 84776}, {'start': 848..."
81,81,Nouns,89670,89771,Other websites,"[{'start': 89669, 'end': 89670}, {'start': 897..."

In [4]:
display(df2)

,link,startIdx,text,endIdx,section,sentid
0,/wiki/Word,74134,word,74176,lead,0
1,/wiki/Part_of_speech,74182,part of speech,74274,lead,0
2,/wiki/Name,74296,name,74338,lead,0
3,/wiki/Person,74362,person,74430,lead,0
4,/wiki/Animal,74700,animal,74748,lead,0
5,/wiki/Idea,74753,idea,74795,lead,0
6,/wiki/English_language,74800,English,74869,lead,1
7,/wiki/Singular,74884,singular,74938,lead,1
8,/wiki/Plural,74942,plural,74990,lead,1
9,/wiki/Article_(grammar),75033,article,75104,lead,2
10,/wiki/Verb,75305,verbs,75348,lead,3
11,/wiki/Adverb,75352,adverbs,75401,lead,3
12,/wiki/Latin,76089,Latin,76134,History,10
13,/wiki/Name,76157,name,76199,History,10
14,/wiki/Sanskrit,76255,Sanskrit,76309,History,11
15,/wiki/Sentence,76731,sentences,76786,Uses of nouns,13
16,/wiki/Subject_(grammar),76811,subject,76882,Uses of nouns,13
17,/wiki/Object_(grammar),76884,object,76952,Uses of nouns,13
18,/wiki/Preposition,77142,prepositions,77206,Uses of nouns,14
19,/wiki/Verb,77519,verb,77561,Uses of nouns,17
20,/wiki/Participle,77717,participles,77778,Uses of nouns,17
21,/wiki/Infinitive,77821,infinitives,77882,Uses of nouns,17
22,/wiki/Pronoun,77954,Pronouns,78006,Uses of nouns,19
23,/wiki/Linguistics,78235,linguists,78296,Uses of nouns,19
24,/wiki/Majuscule,78862,capital,78937,Uses of nouns,22
25,/wiki/English_language,78949,English,79018,Uses of nouns,22
26,/wiki/Roman_alphabet,79057,Roman alphabet,79149,Uses of nouns,22
27,/wiki/German_language,79165,German,79231,Uses of nouns,23
28,/wiki/Tiger,79518,tiger,79563,Uses of nouns,25
29,/wiki/Smith_(metalwork),79569,smith,79638,Uses of nouns,25
30,/wiki/Gods,79906,gods,79968,Uses of nouns,28
31,/wiki/God,79999,God,80038,Uses of nouns,28
32,/wiki/Internet,80179,Internet,80233,Uses of nouns,29
33,/wiki/Singular,80410,singular,80464,Countability,31
34,/wiki/Plural,80528,plural,80576,Countability,31
35,/wiki/Pronunciation,81099,pronunciation,81168,Countability,37
36,/wiki/Phoneme,81253,phoneme,81304,Countability,37
37,/wiki/Morpheme,81371,morpheme,81425,Countability,38
38,/wiki/Morpheme,81437,allomorphs,81493,Countability,38
39,/wiki/Old_English,82357,Old English,82420,Countability,54
40,/wiki/Greek_language,83186,Greek,83249,Countability,67
41,/wiki/Apostrophe,83573,apostrophe,83633,Possessives,70
42,/wiki/Suffix,84161,suffix,84209,How adjectives become nouns,76
43,/wiki/Basic_English,84344,Basic English,84413,How adjectives become nouns,78
44,/wiki/Adjective#100_adjectives_used_in_Basic_E...,84415,click here,84510,How adjectives become nouns,78
45,/wiki/Phrase,84640,phrase,84688,Word order in noun phrases,79
46,/wiki/Determiner,84776,determiners,84837,Word order in noun phrases,80
47,/wiki/Adjective,84839,adjectives,84897,Word order in noun phrases,80

In [5]:
import difflib

clean_sentences_1 = [
    "The quick brown fox jumps over the lazy dog.",
    "Python is a great programming language.",
    "Hello, how are you?",
]

clean_sentences_2 = [
    "The quick brown fox jumps over the lazy dog.",
    "Java is another programming language.",
    "Hello, what's up?",
]

# Create a differ object
d = difflib.Differ()

# Compare the two lists
diff = d.compare(clean_sentences_1, clean_sentences_2)

# Print the differences
for line in diff:
    print(line)

  The quick brown fox jumps over the lazy dog.
- Python is a great programming language.
- Hello, how are you?
+ Java is another programming language.
+ Hello, what's up?